### ISSUE TITLE
Unable to export "lists"

### ISSUE THREAD

**Issue by bre7** [prismagraphql/graphcool-framework#544]
**Please post usage questions or broader discussions in the [Forum](https://www.graph.cool/forum/)**.

For **bug reports**, please fill in the next sections:

**Current behavior**

`lists` always fails to be export.

```bash
λ graphcool export
Downloading nodes... 2240ms
Downloading lists... √
 !    The download of lists failed. You may get fragmented data. Request ID: us-west-xxx
    at ...\\node_modules\graphcool-cli-engine\src\Output\index.ts:209:41
    at SimpleAction.ActionBase.pause (...\\node_modules\graphcool-cli-engine\src\Output\actions\ActionBase.ts:65:17)
    at Output.warn (...\\node_modules\graphcool-cli-engine\src\Output\index.ts:206:17)
    at Exporter.<anonymous> (...\\node_modules\graphcool-cli-core\src\commands\export\Exporter.ts:100:18)
    at step (...\\node_modules\graphcool-cli-core\dist\commands\export\Exporter.js:32:23)
    at Object.next (...\\node_modules\graphcool-cli-core\dist\commands\export\Exporter.js:13:53)
    at fulfilled (...\\node_modules\graphcool-cli-core\dist\commands\export\Exporter.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
Downloading relations... 926ms
```

**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

1. Use the sample project
2. Enter `graphcool export` in your machine

**Expected behavior?**

`nodes`, `lists` and `relations` should be exported

**Comment by bre7** [comment]
Update: I've tried with multiple VPNs so there must be something wrong with the endpoint itself.

**Comment by twelvearrays** [comment]
I also cannot export my lists.  I am trying to migrate to Prisma but I am stuck here.  I have tried VPNs and even a VM on AWS in the same region as my graphcool deployment with no success.

**Comment by gopidon** [comment]
Hi. Any update on this issue? Now that you have sunset Graphcool and we are forced to move to Prisma, this issue is a deal breaker. I am unable to move the date from my Graphcool project to Prisma.

**Comment by bre7** [comment]
The update was that they weren't going to fix it. I somehow managed to migrate to Prisma
